language: node_js
node_js:
  - "10" 
branches:
  only:
    - master
script:
  - "yarn run lint"
  - "yarn test"

install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] then npm install -g firebase-tools && cd ./functions && npm install && cd .. && npm install && npm run build; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy --token $FIREBASE_TOKEN; fi'